config/routes.rb
Rails.application.routes.draw do
  resources :progresses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/progress.rb
class Progress < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController
  before_action :set_progress, only: [:show, :edit, :update, :destroy]

  # GET /progresses
  # GET /progresses.json
  def index
    @progresses = Progress.all
  end

  # GET /progresses/1
  # GET /progresses/1.json
  def show
  end

  # GET /progresses/new
  def new
    @progress = Progress.new
  end

  # GET /progresses/1/edit
  def edit
  end

  # POST /progresses
  # POST /progresses.json
  def create
    @progress = Progress.new(progress_params)

    respond_to do |format|
      if @progress.save
        format.html { redirect_to @progress, notice: 'Progress was successfully created.' }
        format.json { render :show, status: :created, location: @progress }
      else
        format.html { render :new }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progresses/1
  # PATCH/PUT /progresses/1.json
  def update
    respond_to do |format|
      if @progress.update(progress_params)
        format.html { redirect_to @progress, notice: 'Progress was successfully updated.' }
        format.json { render :show, status: :ok, location: @progress }
      else
        format.html { render :edit }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progresses/1
  # DELETE /progresses/1.json
  def destroy
    @progress.destroy
    respond_to do |format|
      format.html { redirect_to progresses_url, notice: 'Progress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress
      @progress = Progress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def progress_params
      params.require(:progress).permit(:user_id, :company_name, :business_category, :occupation_category, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Otokoume</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/progresses/_form.html.erb
<%= form_with(model: progress, local: true) do |form| %>
  <% if progress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(progress.errors.count, "error") %> prohibited this progress from being saved:</h2>

      <ul>
      <% progress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :progress_user_id %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name, id: :progress_company_name %>
  </div>

  <div class="field">
    <%= form.label :business_category %>
    <%= form.number_field :business_category, id: :progress_business_category %>
  </div>

  <div class="field">
    <%= form.label :occupation_category %>
    <%= form.number_field :occupation_category, id: :progress_occupation_category %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status, id: :progress_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/progresses/edit.html.erb
<h1>Editing Progress</h1>

<%= render 'form', progress: @progress %>

<%= link_to 'Show', @progress %> |
<%= link_to 'Back', progresses_path %>

app/views/progresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Progresses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Company name</th>
      <th>Business category</th>
      <th>Occupation category</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @progresses.each do |progress| %>
      <tr>
        <td><%= progress.user_id %></td>
        <td><%= progress.company_name %></td>
        <td><%= progress.business_category %></td>
        <td><%= progress.occupation_category %></td>
        <td><%= progress.status %></td>
        <td><%= link_to 'Show', progress %></td>
        <td><%= link_to 'Edit', edit_progress_path(progress) %></td>
        <td><%= link_to 'Destroy', progress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Progress', new_progress_path %>

app/views/progresses/new.html.erb
<h1>New Progress</h1>

<%= render 'form', progress: @progress %>

<%= link_to 'Back', progresses_path %>

app/views/progresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @progress.user_id %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @progress.company_name %>
</p>

<p>
  <strong>Business category:</strong>
  <%= @progress.business_category %>
</p>

<p>
  <strong>Occupation category:</strong>
  <%= @progress.occupation_category %>
</p>

<p>
  <strong>Status:</strong>
  <%= @progress.status %>
</p>

<%= link_to 'Edit', edit_progress_path(@progress) %> |
<%= link_to 'Back', progresses_path %>